### ISSUE TITLE
unused $add/$action vars using PARAM_RAW

### ISSUE THREAD

**Issue by danmarsden** [streamingltd/moodle-tiny_medial#3]
https://github.com/streamingltd/MEDIAL-Moodle-TinyEditor/blob/master/classes/plugininfo.php#L75-L76

using PARAM_RAW which does no cleaning, but they don't actually appear to be used so might be worth deleting those lines?

**Comment by tim1mw** [comment]
These lines are in use, they hide the MEDIAL button in a small number of places where people should be using the other MEDIAL plugins, although I think this is no longer working for the grading interface. However, this was copied from the older ATTO plugin and looking at it again I think this can be done better, so in the next release I've re-written this to use context information from $PAGE instread of trying to read url parameters directly.

Currently in the private dev version, this will be pushed to git when the next release is made.
