### ISSUE TITLE
capabilities clone permissions from a different plugin that may not be installed

### ISSUE THREAD

**Issue by danmarsden** [streamingltd/moodle-tiny_medial#4]
https://github.com/streamingltd/MEDIAL-Moodle-TinyEditor/blob/master/db/access.php#L39

not sure what happens when a site doesn't have that older atto plugin installed when it does an install - do you? - is this safe? can it be removed?

**Comment by tim1mw** [comment]
I've tested installing the MEDIAL TinyMCE plugin without the presence of the ATTO plugin and I can confirm that the presence of the capability clone for the ATTO plugin does not cause any problems or warnings in the php log, while the capabilitiesare set up correctly. So I think Moodle correctly accounts for the absence of a plugin that it is being asked to clone capabilities from.
