### ISSUE TITLE
duplicate string in lang file

### ISSUE THREAD

**Issue by danmarsden** [streamingltd/moodle-tiny_medial#5]
```
$string['pluginname'] = 'Insert MEDIAL Video';
$string['pluginname'] = 'MEDIAL';
```

also the strings menuitem_insertmedial, menuitem_insertmediallib, helplinktext, newtab may not actually be used in this plugin?

**Comment by tim1mw** [comment]
Fixed in the private dev version, will be part of the next releaase.
