### ISSUE TITLE
Incorrect atto setting check

### ISSUE THREAD

**Issue by sharpchi** [streamingltd/moodle-tiny_medial#7]
Testing tiny_medial without atto_medial installed on PHP 8.3 and M4.5

The tiny_medial_get_defaults function is returning an empty acfg object because atto_medial is not installed.

If you go to the plugin's settings page, you will get an exception because $cfg->hideinsert is not defined.

get_config only returns false if a named field is requested, otherwise it's an object, even if there are no entries found.

Fix change code in tiny_medial_get_defaults to:
```php
if (isset($acfg->hideinsert) && $mcfg === false) {
    return $acfg;
}
```

**Comment by tim1mw** [comment]
Now fixed in the private dev version, this will be part of the next release.
